version: '3.7'

services:
    app:
        build: .
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
        networks:
            - app-network
        environment:
            - APP_ENV=production
            - APP_KEY=base64:txutwI+OPKO4t5iSVVuOMkmPHXBwfoPEyRlubI437MU=
            - DB_CONNECTION=mysql
            - DB_HOST=127.0.0.1
            - DB_PORT=3306
            - DB_DATABASE=test
            - DB_USERNAME=test
            - DB_PASSWORD=

    db:
        image: mysql:5.7
        volumes:
            - db-data:/var/lib/mysql
        networks:
            - app-network
        environment:
            - MYSQL_ROOT_PASSWORD=
            - MYSQL_DATABASE=test
            - MYSQL_USER=root
            - MYSQL_PASSWORD=

networks:
    app-network:

volumes:
    db-data:
